### ISSUE TITLE
Account completion based on date of current transaction

### ISSUE THREAD

**Issue by yegle** [nathangrigg/vim-beancount#15]
It'll be good if the account completion list is based on accounts that's opened at the date of transaction.

E.g. I have a list of accounts like `Expenses:Taxes:TY2014:US:Federal` for year 2014/2015/2016, if I'm entering a transaction today, the account completion should only give `Expenses:Taxes:TY2016:US:Federal`.

**Comment by nathangrigg** [comment]
For people who close accounts, this would be a pretty useful feature.

This would require 

1. Store open/close dates for accounts (easy, since the extractor is Python)
2. On calling completion function with findstart=1, extract the date of the current context (fairly simple).

**Comment by xentac** [comment]
My PR (https://github.com/nathangrigg/vim-beancount/pull/22) has support for looking back at the entire line, so that part is already done.

Right now the bean-query parsing code only supports single column output.  I would recommend waiting till I port it over to python3, so we can use beancount's API from directly within vim.
